server:
  port: 8061

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imgs?characterEncoding=utf-8&serverTimezone=GMT%2B8
    name: imgs
    password: 199777
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
