server:
  port: 8061

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imgs?characterEncoding=utf-8&serverTimezone=GMT%2B8
    name: imgs
    password: 199777
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 30000
    jedis:
      # redis连接池配置
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 32
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 16
        # 最小空闲连接数（默认为0，该值只有为正数才有用）
        min-idle: 8
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: 3000
    database: 20



